name: usfcc26-warpx-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - warpx
  - impactx
  - openmpi
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - openpmd-viewer
  - pip
  - pip:
      - xsuite
      - cpymad
      - numba
